.TH "arestas" 3 "5 Aug 2010" "Version 1.0" "Morphometrics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arestas \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "int \fBvalor\fP"
.br
.ti -1c
.RI "\fBNodo\fP * \fBnodoBase\fP"
.br
.ti -1c
.RI "\fBNodo\fP * \fBnodo\fP"
.br
.ti -1c
.RI "\fBArestas\fP * \fBprox\fP"
.br
.ti -1c
.RI "enum ArestaTipo \fBtipo\fP"
.br
.in -1c
.SH "Descrição Detalhada"
.PP 
Definição na linha 26 do arquivo grafo.h.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Morphometrics a partir de seu código-fonte.
