.TH "Heap" 3 "5 Aug 2010" "Version 1.0" "Morphometrics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Heap \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "int \fBnumElm\fP"
.br
.ti -1c
.RI "int \fBtamanho\fP"
.br
.ti -1c
.RI "void ** \fBelm\fP"
.br
.ti -1c
.RI "int(* \fBfuncao\fP )(void *, void *)"
.br
.in -1c
.SH "Descrição Detalhada"
.PP 
Definição na linha 4 do arquivo heap.h.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Morphometrics a partir de seu código-fonte.
