.TH "nodo" 3 "5 Aug 2010" "Version 1.0" "Morphometrics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nodo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grafo.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "int \fBvalor\fP"
.br
.ti -1c
.RI "int \fBaux\fP"
.br
.ti -1c
.RI "\fBPonto\fP \fBp1\fP"
.br
.ti -1c
.RI "\fBPonto\fP \fBp2\fP"
.br
.ti -1c
.RI "\fBArestas\fP * \fBarestas\fP"
.br
.in -1c
.SH "Descrição Detalhada"
.PP 
Estrutura base dos nodo do grafo 
.PP
Definição na linha 18 do arquivo grafo.h.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Morphometrics a partir de seu código-fonte.
